sonar.projectKey=com.mycompany.myproject
sonar.projectName=My Amazing Project
sonar.projectVersion=1.0
sonar.sources=src
sonar.host.url=http://localhost:8080
sonar.login=sqp_b3643dc5cbd5b1c2efb020c1624505bdb5061f3d  
