name: SonarQube Scan

on:
  push:
    branches:
      - master    # or whichever branch you want to trigger on
  pull_request:
    branches:
      - master    # or whichever branch you want to trigger on

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v1
        with:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Using the SONAR_TOKEN secret


      - name: Run SonarQube Scanner
        run: |
          sonar-scanner -Dsonar.host.url=http://localhost:8080
