name: Java CI with Maven

on:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'  # Add the distribution
        architecture: 'x64'
        check-latest: false

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        organization: my-org
        projectKey: company1234
        projectName: sonarQubeTest
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
