name: SonarQube Scan

on:
  push:
    branches:
      - main   # or whichever branch you want to trigger on
  pull_request:
    branches:
      - main   # or whichever branch you want to trigger on

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: sqp_b3643dc5cbd5b1c2efb020c1624505bdb5061f3d

      - name: Run SonarQube Scanner
        run: |
          sonar-scanner
